id: I2EAAF38A
initial_creation_type: ebook
source_metadata:
  id: BEN-SH-025
  title: ༄༅། །བྱང་ཆུབ་ལམ་གྱི་སྒྲོན་མའི་འགྲེལ་བསྡུས་སྐྱེས་བུའི་ལམ་མཆོག
  author: ''
  authors: &id001 []
  sku: BEN-SH-025
  cover: BEN-SH-025.jpg
  volume: {}
  publisher: བན་ཆེན་གསུང་རབ་རྒྱུན་སྤེལ་ཁང་།
  author_source: none
ebook_metadata:
  title: ༄༅། །བྱང་ཆུབ་ལམ་གྱི་སྒྲོན་མའི་འགྲེལ་བསྡུས་སྐྱེས་བུའི་ལམ་མཆོག
  authors: *id001
  sku: BEN-SH-025
  cover: BEN-SH-025.jpg
layers:
- BookNumber
- BookTitle
- Chapter
- Citation
- Commentary
- Sabche
- SubTitle
- Tsawa
- Yigchung
